### ISSUE TITLE
The links to demos don't work

### ISSUE THREAD

**Issue by rmonishc** [pplonski/artistic-sketches-jupyter-mercury#1]
![image](https://user-images.githubusercontent.com/122089762/211767579-60fc06bb-22aa-400b-8cfb-fddc6b6757a2.png)

I am using a Firefox browser

**Comment by pplonski** [comment]
Thanks @rmonishc for reporting! Are you running Mercury locally? What do you get when you click on link?

**Comment by rmonishc** [comment]
> 

So, I was just downloading Mercury to use locally. I wanted to see the demo on a browser but the link to the herokuapp does not seem to load. Perhaps I need to install something before I can access it?

**Comment by pplonski** [comment]
Heroku switched off the free tier in November 2023. Our demo apps are not working ...

We are working now on Mercury Version 2 and cloud offering (you will just upload a notebook and your website will be created, with custom subdomain).

**Comment by rmonishc** [comment]
> 

So that's it then! Thanks for replying :D
